<?php
// $Id: library_footer.module,v 1.0 2013/07/25 17:25:08 dmoses Exp $

/*
 * Implementation of hook_theme().
 */
function upei_footer_theme() {
  return array(
    'library_footer_footer' => array('arguments' => array(), 'template' => 'library-footer-footer')
  );
}

function library_footer_block_info() {
  $blocks['library_footer'] = array(
    'info' => t('Library footer'), //The name that will appear in the block list.
    'cache' => DRUPAL_CACHE_PER_ROLE, //Default
  );
  return $blocks;
}

function library_footer_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'library_footer':
      $block['subject'] = t('');
      $block['content'] = theme('library_footer_footer');
      return $block;
    break;
  }

}

function library_footer_preprocess_library_footer_footer(&$variables) {
  $request = drupal_http_request('files/misc/library_footer.txt');
  $data = $request->data;
  $request_code = $request->code;
  if ($request_code === "200") {
    $variables['external_php'] = $data;
  }
}
