<?php
// $Id: upei_footer.module,v 1.0 2013/01/22 17:25:08 krisbulman Exp $
// update for the library footer
/*
 * Implementation of hook_theme().
 */
function upei_library_footer_theme() {
  return array(
    'upei_library_footer_footer' => array('arguments' => array(), 'template' => 'upei-library-footer-footer')
  );
}

function upei_library_footer_block_info() {
  $blocks['upei_library_footer'] = array(
    'info' => t('UPEI Library footer'), //The name that will appear in the block list.
    'cache' => DRUPAL_CACHE_PER_ROLE, //Default
  );
  return $blocks;
}

function upei_library_footer_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'upei_library_footer':
      $block['subject'] = t('');
      $block['content'] = theme('upei_library_footer_footer');
      return $block;
    break;
  }

}

function upei_library_footer_preprocess_upei_library_footer_footer(&$variables) {
/*  $request = drupal_http_request('http://www.upei.ca/becomeastudent/files/misc/footer.php'); */
$request = drupal_http_request('http://137.149.200.37/content//sites/137.149.200.37.content/files/misc/library_footer.txt');
  $data = $request->data;
  $request_code = $request->code;
  if ($request_code === "200") {
    $variables['external_php'] = $data;
  }
}
